Repository datapartnership/gaza-israel-conflict-impact-analysis, pull requests merged in 2024-02, with the labels that each got.

#22 Create Solar Panel Detection
  docs/_toc.yml
  docs/team.md
  notebooks/damage-assessment/README.md
  notebooks/solar-panel-segmentation/README.md
  notebooks/solar-panel-segmentation/panel-detection-gaza.ipynb
  notebooks/solar-panel-segmentation/requirements.txt
  notebooks/solar-panel-segmentation/setup.cfg
  notebooks/solar-panel-segmentation/setup.py
  notebooks/solar-panel-segmentation/versioneer.py
Labels: solar-panel-detection

#32 Add estimation of OSM buildings without electricity
  notebooks/sample-indicators/housing-and-community.ipynb
  notebooks/sample-indicators/industry-and-commerce.ipynb
Labels: nighttime-lights

#47 Add bibliography and citation
  CITATION.cff
  README.md
  docs/bibliography.bib
  notebooks/nighttime-lights/nighttime-lights.ipynb
  pyproject.toml
  reports/README.md
Labels: documentation
